### PR TITLE
[BUGFIX] Linkbrowser fix

### LINKED ISSUE #509: LinkBrowser and canonical link
### Prerequisites:
1. typo3 10.4.36 / Typo3 11.5.26
2. Templavoilaplus 8.1.3

Related to #451 and #502 

Unfortunately with the latest version and the bugfix for the link browser, the canonical link field doesn't work in all cases.

---

Typo3 11:
image

Next  step:
image

Then when you select an item in the linkbrowser window there is no value in the input.

----
Typo3 10:
image

Next  step:
image

Then when you select an item in the linkbrowser window there is no value in the input.

### PR DESCRIPTION
**Pull request by gregordonsky**
A more robust approach that fixes item selection in linkbrowser.
This version will remove JavaScriptModuleInstruction xClass and just use only LinkBrowserController as xClass
ParentWindow is a new requireJS module which integrate only the getParent function in FormEngineLinkBrowserAdapter.
Compatible with typo3 9, 10, 11. Must be tested in v. 12.

LinkBrowserController is an xClass of ext:backend so you need to evaluate if the directory structure is correct or if you like having an xClass folder.

The file [Configuration/Backend/Routes.php](https://github.com/T3Voila/templavoilaplus/blob/fb9ff0c865b34299540b803ef3c7726b6bdd08c2/Configuration/Backend/Routes.php) in the main branch should be used for all typo3 versions.

I think that this will definitely fix #509 #502 #451

I get inspired by the solution i found in https://github.com/FriendsOfTYPO3/frontend_editing/issues/457 .
You can check it and https://github.com/FriendsOfTYPO3/frontend_editing/pull/656 if you want to use a service instead of LinkBrowserController xclass.
In this case the code will be compatible only with typo3 version >= 11 because BootCompletedEventHandler is only defined by v.11

### CODE REVIEW

**Comment by opi99** [comment]
Ok, understand, but could you rework this patch a bit?

Do not delete the existing solution, as it works in TYPO3 v8 and yours only from TYPO3 v9 on.
So adding a version_compare() before XClassing and maybe. Would only take this for the 8.x branch and in the 11.x (main) branch adding the service variant.

**Review by opi99 — CHANGES_REQUESTED** [review]
Do not delete the existing solution, as it works in TYPO3 v8 and yours only from TYPO3 v9 on.
So adding a version_compare() before XClassing and maybe. Would only take this for the 8.x branch and in the 11.x (main) branch adding the service variant.

**Comment by gregordonsky** [comment]
Hi @opi99,

I don't remember very well, but I think I didn't mention v.8 because I haven't tested the code in typo3 v.8 environment.
I checked the typo3 v.8 source code and I think this patch should be compatible with this version as well.

Have you checked this in a typo3 v.8 environment? Unfortunately when I created this code I didn't have a v.8 to verify if everything was ok...

**Comment by opi99** [comment]
Closing in favor #528

**Pull request closed without merging**
